baseURL = "https://joshpinto6.github.io/GodotMage/site"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"

[params.settings123]

  Title = "GodotMage"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "Tutorials"
  URL = "https://joshpinto6.github.io/GodotMage/docs"
  weight = 2

  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 3

  [[menu.header]]
  name = "Blog"
  URL = "https://joshpinto6.github.io/GodotMage/docs/blog"
  weight = 6

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 6

  [[menu.header]]
  name = "Github"
  URL = "https://github.com/joshpinto6/GodotMage"
  weight = 8

  
  [[menu.footer]]
  name = "Tutorials"
  URL = "https://joshpinto6.github.io/GodotMage/docs"
  weight = 2

  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 3

  [[menu.footer]]
  name = "Blog"
  URL = "https://joshpinto6.github.io/GodotMage/docs/blog"
  weight = 4

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 5

  [[menu.footer]]
  name = "Github"
  URL = "https://github.com/joshpinto6/GodotMage"
  weight = 6


[params]

  sections = ["showcase", "about", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter"]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "GodotMage"
    text2 = ""
    image = "img/logo_outline.svg"

  [params.footer]
      copyright = "© 2022 GodotMage. All rights reserved."
      disclaimer = "*Not affiliated with or endorsed by the Godot Game Engine."
      notice = "Made with ♥ with [Hugo](https://gohugo.io) & [Raditian](https://github.com/radity/raditian-free-hugo-theme) Theme"
     
