name: 🐱‍🐉 Build Documentation

on: 
    push:
        branches:
         - master
        paths:
         - docs/**
    workflow_dispatch:
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  cancel-workflow-runs:
   name: Cancel Previous Runs 
   runs-on: ubuntu-latest
   steps:
    - name: Cancel Previous Workflow Runs
      uses: n1hility/cancel-previous-runs@v2.0
  build:
    needs: [cancel-workflow-runs]
    name: Build with Docusaurus
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./docs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache-dependency-path: './docs/package-lock.json'
          node-version: 18
          cache: npm

      - name: Install dependencies
        working-directory: ./docs
        run: npm ci
      - name: Build website
        working-directory: ./docs
        run: npm run build
        
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: docs/build/ # or path/to/artifact
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
        
#       - name: Fetch action
#         id: pl
#         uses: Rishabh510/Path-lister-action@master
#         with:
#           path: "docs/"
#           type: ".html"
          
#       - name: Output results
#         run: |
#           echo "Found ${{ steps.pl.outputs.path_count }} file(s) with this extension:"
#           for i in ${{ steps.pl.outputs.paths }}; do
#           echo $i
#           done

